### ISSUE TITLE
Finetune setting `ask_before_closing`

### ISSUE THREAD

**Issue by kitzberger** [ddbln/CloseAllNoConfirm#2]
Hi Dirk,

nice addon, it's exactly what I've been waiting for ;-)

In #1 you've introduced the `ask_before_closing`. I was wondering if the behaviour for "true" should really be closing all windows' views and not rather only the current windows' views.

The default is to ask. If I don't wanna be asked I set the setting to false and probably wanna close the views that I'm currently seeing, right? Now that I think about it, there might be people wanting the exact opposite ;-)

:thinking: This would make it necessary to add a three option setting or add a new one.

:bulb: Why not remove the setting and add a parameter to the command? This way people could defined multiple key-mappings for different use cases.

**Comment by ddbln** [comment]
Hi Philipp, 

thank you for the feedback and for taking the time to understand the intricacies of the plugin! That is a great suggestion and it makes a lot of sense. I will look into implementing this in a future update soon. Thanks for your thoughts!

**Comment by ddbln** [comment]
@kitzberger Thank's again for your contribution! Since this is now merged, i think we can close this issue for now? I also think there are different user groups, so i think it's good to foremost let the users decide, if they even want to be asked at all.  If they choose not to, i think it's reasonable to have the plugin take action immediately. With your new option, users can now configure its behavior to suit their needs and for those who still prefer to be prompted, there's still just one prompt, allowing them to decide where they want to close. Let's see how it performs in practice :-)
